name: CI
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp-version: [23, 24, 25]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: '1.14'
      - name: DIALYZE
        run: make dialyze
      - name: TEST
        run: make tests
      - name: ON FAILRUE ARCHIVE TESTS LOGS
        if: failure()
        run: make ct-logs-archive
      - name: ON FAILURE UPLOAD TESTS LOGS ARTIFACT
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ct-logs
          path: "*-ct-logs-*.tar.xz"
  test-bazel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp-version: [23, 24, 25]
        elixir-version: ['1.14']
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - name: MOUNT BAZEL CACHE
        uses: actions/cache@v3
        with:
          path: "/home/runner/repo-cache/"
          key: repo-cache
      - name: CONFIGURE BAZEL
        run: |
          ERLANG_HOME="$(dirname $(dirname $(which erl)))"
          ELIXIR_HOME="$(dirname $(dirname $(which iex)))"
          cat << EOF >> .bazelrc
            build --repository_cache=/home/runner/repo-cache/
            build --color=yes
            build --disk_cache=
            build --incompatible_strict_action_env
            build --local_test_jobs=1
          EOF
      - name: RUN TESTS
        run: |
          bazelisk test //... \
            --verbose_failures
